name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Navigate to app directory
      - name: Change Directory to /app
        working-directory: ./app
        run: echo "Navigated to app directory"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run Linters
      - name: Run ESLint
        run: npm lint
        env:
          CI: true

      # Step 6: Run Tests
      - name: Run Tests
        run: npm test -- --watchAll=false
        env:
          CI: true

      # Step 7: Check for Formatting
      - name: Run Prettier
        run: npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,scss,md}"

      # Step 8: Run Type Checking
      - name: Run TypeScript Check (if applicable)
        run: npx tsc --noEmit

      # Optional: Add Logs
      - name: Logs
        run: echo "All checks passed successfully!"

      # Step 9: Report Success
      - name: Completion
        run: echo "CI Pipeline Completed Successfully"
