name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Navigate to app directory and install dependencies
      - name: Install dependencies
        working-directory: ./app
        run: npm install

      # Step 4: Run Linters
      - name: Run ESLint
        working-directory: ./app
        run: npm run lint
        env:
          CI: true

      # Step 5: Run Tests
      # - name: Run Tests
      #   working-directory: ./app
      #   run: npm test -- --watchAll=false
      #   env:
      #     CI: true

      # Step 6: Check for Formatting
      - name: Run Prettier
        working-directory: ./app
        run: npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,scss,md}"

      # Step 7: Run Type Checking (if applicable)
      - name: Run TypeScript Check
        working-directory: ./app
        run: npx tsc --noEmit

      # Optional: Add Logs
      - name: Logs
        run: echo "All checks passed successfully!"

      # Step 8: Report Success
      - name: Completion
        run: echo "CI Pipeline Completed Successfully"

      # Step 9: Report Success
      - name: Completion
        run: echo "CI Pipeline Completed Successfully"
